# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80e1184bc9b2c95f988451d2bd969f44e9137382318dafb8c357e5bcb9591f312ec0bde96929e2a50c3acaf9090b5e462c6bc112feab31f53672207cf2093556

test:
  secret_key_base: 89e2e7960a6882573cdd65b09e3a9af346ba5892833520623a0a13b19cbfef26264bca253621a83280b36b2a4bd6aa0543c4968a3ba478497d97e89af38e9c90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
